package edu.rosehulman.summarizer;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Properties;

import edu.stanford.nlp.io.IOUtils;
import edu.stanford.nlp.ling.CoreAnnotations;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.pipeline.Annotation;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;
import edu.stanford.nlp.stats.ClassicCounter;
import edu.stanford.nlp.stats.Counter;
import edu.stanford.nlp.util.CoreMap;

/*	Summarizes a document based on a model file generated by either
 *  Preprocess.java or PreprocessRec.java
 *  
 *  Ben, your turn.
 */
public class DocumentSummarizer {

	Counter<String> df;
	int numDocuments;
	
	private static final StanfordCoreNLP pipeline;
	private static final Properties props;
	static {
		props = new Properties();
		props.setProperty("annotators","tokenize,ssplit,pos");
		props.setProperty("tokenize.language","en");
		props.setProperty("pos.model","edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger");
		pipeline = new StanfordCoreNLP(props);
	}

	public DocumentSummarizer(Counter<String> df) throws Exception {
		this.df = df;
		this.numDocuments = (int) df.getCount("numDocuments");
	}
	
	public String summarize(String document, int numSentences) {
		Annotation annotation = pipeline.process(document);
		List<CoreMap> sentences = annotation.get(CoreAnnotations.SentencesAnnotation.class);
		//Counter<String> TF = calcTF(sentences);
		Counter<String> TF = new ClassicCounter<String>();
		for (CoreMap sentence : sentences) {
			for (CoreLabel token : sentence.get(CoreAnnotations.TokensAnnotation.class)) {
				TF.incrementCount(token.get(CoreAnnotations.TextAnnotation.class));
			}
		}
		Collections.sort(sentences, new SentenceComparator(TF));
		StringBuilder summary = new StringBuilder();
		for (int i = 0; i < numSentences; i++) {
			summary.append(sentences.get(i));
			summary.append(" ");
		}
		return summary.toString();
	}
	
	private class SentenceComparator implements Comparator<CoreMap> {
		
		private final Counter<String> TF;
		
		public SentenceComparator(Counter<String> TF) {
			this.TF = TF;
		}
		
		public int compare(CoreMap sentence1, CoreMap sentence2) {
			int index1 = sentence1.get(CoreAnnotations.SentenceIndexAnnotation.class);
			int index2 = sentence2.get(CoreAnnotations.SentenceIndexAnnotation.class);
			// sentences closer to the beginning are more important
			return (int) Math.round(calcTFIDF(sentence2)/index2 - calcTFIDF(sentence1)/index1);
		}
		
		private double calcTFIDF(CoreMap sentence) {
			double tfidf = 0;
			List<CoreLabel> tokens = sentence.get(CoreAnnotations.TokensAnnotation.class);
			for (CoreLabel token : tokens) {
				String pos = token.getString(CoreAnnotations.PartOfSpeechAnnotation.class);
				if (pos.startsWith("n") || pos.startsWith("N")) {
					String text = token.getString(CoreAnnotations.TextAnnotation.class);
					if (df.getCount(text) != 0) {
						double tf = 1 + Math.log(TF.getCount(text));
						double idf = Math.log(numDocuments / (1 + df.getCount(text)));
						tfidf += tf*idf;
					}
				}
			}
			return tfidf;
		}

	}
	
	@SuppressWarnings("unchecked")
	public static void main(String[] args) throws Exception {
		String documentPath = args[0];
		String content = IOUtils.slurpFile(documentPath);
		
		String dfPath = args[1];
		ObjectInputStream stream = new ObjectInputStream(new FileInputStream(dfPath));
		Counter<String> df = (Counter<String>) stream.readObject();
		stream.close();
		
		DocumentSummarizer summarizer = new DocumentSummarizer(df);
		String result = summarizer.summarize(content, 2);
		System.out.println(result);
	}
	
}
